export const events = [
  {
    image: "/event1.png",
    title: "Hackathon Summit 2025",
    slug: "hackathon-summit-2025",
    location: "Bangalore, India",
    date: "Nov 15, 2025",
    time: "10:00 AM - 6:00 PM",
  },
  {
    image: "/event2.png",
    title: "Next.js Conf 2025",
    slug: "nextjs-conf-2025",
    location: "San Francisco, USA",
    date: "Dec 1, 2025",
    time: "9:00 AM - 5:00 PM",
  },
  {
    image: "/event2.png",
    title: "AI Developers Meetup",
    slug: "ai-developers-meetup",
    location: "Pune, India",
    date: "Nov 22, 2025",
    time: "2:00 PM - 8:00 PM",
  },
  {
    image: "/event1.png",
    title: "Open Source India 2025",
    slug: "open-source-india-2025",
    location: "Hyderabad, India",
    date: "Dec 10, 2025",
    time: "9:30 AM - 4:30 PM",
  },
  {
    image: "/event2.png",
    title: "Frontend Dev Fest",
    slug: "frontend-dev-fest",
    location: "Berlin, Germany",
    date: "Jan 5, 2026",
    time: "11:00 AM - 7:00 PM",
  },
  {
    image: "/event1.png",
    title: "Cloud Native Summit",
    slug: "cloud-native-summit",
    location: "Singapore",
    date: "Jan 18, 2026",
    time: "9:00 AM - 6:00 PM",
  },
  {
    image: "/event2.png",
    title: "Web3 Innovators Meetup",
    slug: "web3-innovators-meetup",
    location: "Mumbai, India",
    date: "Feb 2, 2026",
    time: "5:00 PM - 9:00 PM",
  },
  {
    image: "/event1.png",
    title: "Global Tech Expo 2026",
    slug: "global-tech-expo-2026",
    location: "Dubai, UAE",
    date: "Feb 15–17, 2026",
    time: "10:00 AM - 8:00 PM",
  },
];